name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./my-first-pokedex-coda
        run: npm ci

      - name: Build
        working-directory: ./my-first-pokedex-coda
        run: npm run build

      - name: Run
        working-directory: ./my-first-pokedex-coda
        run: npm run dev & npx wait-on http://localhost:5173/JavaScript---Pokedex/

      - name: GreenIT Analysis
        uses: ythirion/greenit-analysis-action@0.1.1

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'my-first-pokedex-coda/dist/'
          retention-days: '30'

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: ./my-first-pokedex-coda
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./my-first-pokedex-coda
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./my-first-pokedex-coda
        run: npm run accessibility
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4